SELECT
a.AN_ID AS Id,
a.AN_BIRTH_DATE,
a.AN_SEX AS gender,
a.AN_SP_CODE AS species,
SUBSTRING(c.CON_BIRTHPLACE, 1, 7) AS room,
SUBSTRING(c.CON_BIRTHPLACE, 8, 2) AS cage,
(CASE WHEN a.AN_BIRTH_DATE_EST = 'E' THEN 1 ELSE 0 END) AS date_type,
a.AN_BIRTH_VIABILITY AS birth_viability,
c.CON_CON_DATE AS conception,
c.CON_CON_DATE_STATUS AS conceptionDateStatus,
a.AN_BIRTH_DELIVERY_MODE AS "type", --birth_type
-- AS objectid
FROM cnprcSrc.ZANIMAL a
LEFT JOIN cnprcSrc.ZCONCEPTION c
ON a.AN_ID = c.CON_OFFSPRING_ID
WHERE a.AN_ACQ_TYPE = '0'