SELECT
AB_AN_ID AS id,
AB_BOOK AS book,
AB_MALE_ENEMY_1 AS maleEnemy1,
AB_MALE_ENEMY_2 AS maleEnemy2,
AB_MALE_ENEMY_3 AS maleEnemy3,
AB_MALE_ENEMY_4 AS maleEnemy4,
AB_MALE_ENEMY_5 AS maleEnemy5
--  AS objectId,
FROM cnprcSrc.ZAN_BREEDING;