SELECT
BR_FEMALE_ID AS Id,
BR_BREEDING_DATE,
BR_MALE_ID AS sire,
BR_HOURS AS hours,
BR_OBS_CODE AS obsCode,
BR_CYCLE_DAY AS cycleDay,
BR_CYCLE_DAY1_DATE AS cycleStartDate,
OBJECTID as objectid
FROM cnprcSrc.ZBREEDING
