SELECT
TRIM(SUBSTRING(ZH_LOCATION_ID, 1, 7)) || '-' || TRIM(SUBSTRING(ZH_LOCATION_ID, 8, 2))AS  location,
ZH_PK AS location_history_pk,
ZH_CAGE_SIZE AS cage_size,
CASE
  WHEN ZH_CAGE_SIZE IS NULL THEN NULL
  WHEN TRIM (
    TRANSLATE (ZH_CAGE_SIZE,'1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ', '1234567890')
    ) = '' THEN NULL
  ELSE
  CAST (
    TRANSLATE (ZH_CAGE_SIZE,'1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ', '1234567890')
    AS INTEGER)
    END
    AS cage_size_number,
ZH_RATE_CLASS AS rate_class,
ZH_FROM_DATE AS from_date,
ZH_TO_DATE AS to_date,
ZH_FILE_STATUS AS file_status,
OBJECTID AS objectid,
DATE_TIME
FROM
cnprcSrc.ZLOCATION_HISTORY
WHERE
(ZH_TO_DATE is null or ZH_TO_DATE > to_date('01-01-1900', 'DD-MM-YYYY') AND ZH_FROM_DATE > to_date('01-01-1900', 'DD-MM-YYYY'));