SELECT
ANCENS_AN_ID AS Id,
ANCENS_FLAG_ASSIGNED AS assignedDate,
ANCENS_FLAG_REMOVED AS enddate,
ANCENS_CODE AS flag
FROM cnprcSrc.ZAN_CENSUS_FLAG_HISTORY
UNION ALL
SELECT
ANCOL_AN_ID AS Id,
ANCOL_ASSIGNMENT_DATE AS assignedDate,
ANCOL_RELEASE_DATE AS enddate,
ANCOL_COLONY_CODE AS flag
FROM cnprcSrc.ZAN_COLONY;