SELECT
FORMULARY_DOSING_PK AS formulary_dosing_id,
FORMULARY_NAME_FK AS formulary_name_fk,
(CASE WHEN DOSING_RECORD_ACTIVE_YN = 'Y' THEN 1 ELSE 0 END) AS dosing_record_active,
(CASE WHEN FORMULARY_DATA_COMPLETE_YN = 'Y' THEN 1 ELSE 0 END) AS formulary_data_complete,
DRUG_FORMAT_DESCRIPTION AS drug_format_description,
CONCENTRATION_UNITS AS concentration_units,
CONCENTRATION_PER_UNIT AS concentration_per_unit,
DOSE_UNITS AS dose_units,
DOSE_PER_UNIT AS dose_per_unit,
DOSE_PER_UNIT_MIN AS dose_per_unit_min,
DOSE_PER_UNIT_MAX AS dose_per_unit_max,
ROUTE AS route,
FREQUENCY AS frequency,
DAYS_DURATION AS days_duration,
TREATMENT_VOLUME_UNITS AS treatment_volume_units,
DOSE_SPECIFIC_COMMENT AS dose_specific_comment,
WEIGHT_RANGE_LOWER_LIMIT AS weight_range_lower_limit,
WEIGHT_RANGE_UPPER_LIMIT AS weight_range_upper_limit,
BILLING_ITEM_CODE AS billing_item_code,
FROM cnprcSrc.ZPRIMED_FORMULARY_DOSING;
