SELECT
PR_AN_ID AS Id,
PR_DATE,
PR_PROJECT AS projectCode,
POT_ORGAN AS organ,
PR_REPORT_TYPE AS reportType,
POT_TEXT AS remark,
ot.OBJECTID as objectid,
CAST(CASE WHEN(ot.DATE_TIME > pr.DATE_TIME)
  THEN
    ot.DATE_TIME
  ELSE pr.DATE_TIME
END AS TIMESTAMP) AS date_time
FROM
cnprcSrc.ZPATH_ORGAN_TEXT ot
LEFT JOIN
cnprcSrc.ZPATH_REPORT pr
ON
ot.POT_FK = pr.PR_PK;