SELECT
RELOC_AN_ID AS Id,
RELOC_DATE_IN,
RELOC_DATE_OUT AS enddate,
(CASE WHEN RELOC_LOCATION_PREFIX = '0200' THEN RTRIM(SUBSTRING(RELOC_LOCATION, 1, 7)) ELSE NULL END) AS room,
(CASE WHEN RELOC_LOCATION_PREFIX = '0200' THEN RTRIM(SUBSTRING(RELOC_LOCATION, 8, 2)) ELSE NULL END) AS cage,
-- AS divider,
-- AS housingCondition,
-- AS housingType,
RELOC_SALE_COMMENT AS reason,
OBJECTID AS objectid,
DATE_TIME
FROM cnprcSrc.ZRELOCATION
WHERE RELOC_LOCATION IS NOT NULL;