SELECT
INST_IID AS id,
INST_NAME AS "name",
INST_ABBREV AS abbreviation,
INST_CITY AS city,
INST_STATE AS state,
INST_COUNTRY AS country,
INST_FILE_STATUS AS fileStatus,
INST_RECORD_CLASS AS recordClass
FROM cnprcSrc.ZINSTITUTION;