SELECT
AM_FEMALE_ID AS Id,
AM_MATING_DATE,
AM_MALE_ID AS male,
AM_HOURS_TO_BREED AS hours,
AM_CYCLE_DAY1_DATE AS cycleStartDate,
AM_CYCLE_DAY AS cycleDay,
AM_LOCATION_OVERRIDE AS locationOverride,
AM_WEEKEND_BREEDING AS weekendBreeding,
AM_WEEKEND_BREEDING_STATE AS weekendBreedingState
FROM cnprcSrc.ZAN_MATING;
