SELECT
MHO_FILE_NO AS fileNum,
MHO_REC_SEQ AS sequence,
MHO_REC_TYPE AS recordType,
MHO_REC_STATUS AS recordStatus,
MHO_REC_TEXT AS remark,
MHO_BEGIN_DATE,
MHO_FULL_DATE AS fullDate,
MHO_ENCLOSURE AS room,
MHO_AREA AS area,
MHO_OBS_CODE_LIST AS observation,
MHO_OBS_CODE_1 AS obsCode1,
MHO_OBS_CODE_2 AS obsCode2,
MHO_OBS_CODE_3 AS obsCode3,
MHO_OBS_CODE_4 AS obsCode4,
MHO_TECHNICIAN AS technician,
MHO_ATTENDANT AS attendant
FROM cnprcSrc.MH_OBS
WHERE
MHO_AN_ID IS NOT NULL AND
MHO_AN_ID = 'ROOM' AND
MHO_BEGIN_DATE IS NOT NULL AND
MHO_ENCLOSURE IS NOT NULL;
