SELECT
MHO_FILE_NO AS fileNum,
MHO_REC_SEQ AS sequence,
MHO_REC_TYPE AS recordType,
MHO_REC_STATUS AS recordStatus,
MHO_REC_TEXT AS remark,
MHO_AN_ID AS Id,
MHO_BEGIN_DATE,
MHO_FULL_DATE AS fullDate,
MHO_ENCLOSURE AS enclosure,
SUBSTRING(MHO_LOCATION, 8, 2) AS cage,
MHO_AREA AS area,
MHO_RAW_AN_ID AS rawId,
MHO_RAW_LOCATION AS raw_location,
MHO_OBS_CODE_LIST AS observation,
MHO_OBS_CODE_1 AS obsCode1,
MHO_OBS_CODE_2 AS obsCode2,
MHO_OBS_CODE_3 AS obsCode3,
MHO_OBS_CODE_4 AS obsCode4,
MHO_OBS_CODE_5 AS obsCode5,
MHO_OBS_CODE_6 AS obsCode6,
MHO_OBS_CODE_7 AS obsCode7,
MHO_OBS_CODE_8 AS obsCode8,
MHO_OBS_CODE_9 AS obsCode9,
MHO_OBS_CODE_10 AS obsCode10
-- MHP_TECHNICIAN AS technician,
-- MHP_ATTENDANT AS attendant
FROM cnprcSrc.MH_OBS
WHERE
MHO_AN_ID IS NOT NULL AND MHO_AN_ID != 'ROOM' AND MHO_BEGIN_DATE IS NOT NULL;
