SELECT
HOG_CODE AS obsCode,
HOG_SNOMED_CODE_1 AS snomedCode,
HOG_PREGNANCY_DISPLAY_FLAG AS pregnancyDisplayFlag,
HOG_VISUAL_SIGNS_ONLY_FLAG AS visualSignsOnlyFlag
FROM cnprcSrc.ZHEALTH_OBS_GLOSSARY WHERE HOG_SNOMED_CODE_1 IS NOT NULL

UNION ALL

SELECT
HOG_CODE AS obsCode,
HOG_SNOMED_CODE_2 AS snomedCode,
HOG_PREGNANCY_DISPLAY_FLAG AS pregnancyDisplayFlag,
HOG_VISUAL_SIGNS_ONLY_FLAG AS visualSignsOnlyFlag
FROM cnprcSrc.ZHEALTH_OBS_GLOSSARY WHERE HOG_SNOMED_CODE_2 IS NOT NULL

UNION ALL

SELECT
HOG_CODE AS obsCode,
HOG_SNOMED_CODE_3 AS snomedCode,
HOG_PREGNANCY_DISPLAY_FLAG AS pregnancyDisplayFlag,
HOG_VISUAL_SIGNS_ONLY_FLAG AS visualSignsOnlyFlag
FROM cnprcSrc.ZHEALTH_OBS_GLOSSARY WHERE HOG_SNOMED_CODE_3 IS NOT NULL

UNION ALL

SELECT
HOG_CODE AS obsCode,
HOG_SNOMED_CODE_4 AS snomedCode,
HOG_PREGNANCY_DISPLAY_FLAG AS pregnancyDisplayFlag,
HOG_VISUAL_SIGNS_ONLY_FLAG AS visualSignsOnlyFlag
FROM cnprcSrc.ZHEALTH_OBS_GLOSSARY WHERE HOG_SNOMED_CODE_4 IS NOT NULL

UNION ALL

SELECT
HOG_CODE AS obsCode,
HOG_SNOMED_CODE_5 AS snomedCode,
HOG_PREGNANCY_DISPLAY_FLAG AS pregnancyDisplayFlag,
HOG_VISUAL_SIGNS_ONLY_FLAG AS visualSignsOnlyFlag
FROM cnprcSrc.ZHEALTH_OBS_GLOSSARY WHERE HOG_SNOMED_CODE_5 IS NOT NULL

UNION ALL

SELECT
HOG_CODE AS obsCode,
HOG_SNOMED_CODE_6 AS snomedCode,
HOG_PREGNANCY_DISPLAY_FLAG AS pregnancyDisplayFlag,
HOG_VISUAL_SIGNS_ONLY_FLAG AS visualSignsOnlyFlag
FROM cnprcSrc.ZHEALTH_OBS_GLOSSARY WHERE HOG_SNOMED_CODE_6 IS NOT NULL

UNION ALL

SELECT
HOG_CODE AS obsCode,
HOG_SNOMED_CODE_7 AS snomedCode,
HOG_PREGNANCY_DISPLAY_FLAG AS pregnancyDisplayFlag,
HOG_VISUAL_SIGNS_ONLY_FLAG AS visualSignsOnlyFlag
FROM cnprcSrc.ZHEALTH_OBS_GLOSSARY WHERE HOG_SNOMED_CODE_7 IS NOT NULL

UNION ALL

SELECT
HOG_CODE AS obsCode,
HOG_SNOMED_CODE_8 AS snomedCode,
HOG_PREGNANCY_DISPLAY_FLAG AS pregnancyDisplayFlag,
HOG_VISUAL_SIGNS_ONLY_FLAG AS visualSignsOnlyFlag
FROM cnprcSrc.ZHEALTH_OBS_GLOSSARY WHERE HOG_SNOMED_CODE_8 IS NOT NULL;