SElECT
PRTA_ID AS protocolAmendmentId,
PRTA_AUCAAC_NUMBER AS protocol,
(CASE WHEN PRTA_AMENDMENT_APPROVED_YN = 'Y' THEN 1 ELSE 0 END) AS approved,
PRTA_COMMITTEE_RESPONSE_DATE AS committeeResponseDate,
PRTA_SP1_ADDITIONAL_ALLOWED AS sp1AdditionalAllowed,
PRTA_SP2_ADDITIONAL_ALLOWED AS sp2AdditonalAllowed,
PRTA_AMENDMENT_COMMENT AS amendmentComments,
OBJECTID AS objectid,
DATE_TIME
FROM cnprcSrc.ZPROTOCOL_AMENDMENT
WHERE
PRTA_ID IS NOT NULL AND
PRTA_COMMITTEE_RESPONSE_DATE > to_date('01-01-1900', 'DD-MM-YYYY');