SELECT
APE_ID AS id,
APE_AUCAAC_NUMBER AS protocol,
APE_AN_ID AS animalId,
APE_EXCEPTION_CODE AS exceptionCode,
APE_COMMENT AS comments,
OBJECTID AS objectid,
DATE_TIME
FROM cnprcSrc.ZAN_PROTOCOL_EXCEPTIONS;