SELECT
PDET_FEMALE_ID AS Id,
PDET_SAMPLE_DATE,
PDET_METHOD AS method,
PDET_RESULT AS result,
PDET_SCHEDULE_STATUS AS scheduleStatus,
PDET_CYCLE_DAY1_DATE AS cycleDay1,
CON_TERM_DATE AS termDate,
CON_PR_CODE AS termCode,
CON_CON_DATE AS confirmDate,
-- lastObscanDate,
CON_MALE_ID AS sire,
-- objectId
FROM
cnprcSrc.ZPG_DETERMINATION pd
LEFT JOIN cnprcSrc.ZCONCEPTION con
ON pd.PDET_FEMALE_ID = con.CON_FEMALE_ID
WHERE PDET_SAMPLE_DATE > to_date('01-01-1900', 'DD-MM-YYYY');


