SELECT
PDET_FEMALE_ID AS Id,
PDET_SAMPLE_DATE,
PDET_METHOD AS method,
PDET_RESULT AS result,
PDET_SCHEDULE_STATUS AS scheduleStatus,
PDET_CYCLE_DAY1_DATE AS cycleDay1,
OBJECTID as objectid
FROM
cnprcSrc.ZPG_DETERMINATION pd
WHERE PDET_SAMPLE_DATE > to_date('01-01-1900', 'DD-MM-YYYY');


