SELECT
ENCL_ENCLOSURE_ID AS room,
ENCL_FILE_STATUS AS file_status,
ENCL_MANAGEMENT_TYPE AS management_type,
ENCL_SUPERVISOR AS supervisor,
ENCL_WEIGHT_SHEET_FREQUENCY AS weight_sheet_frequency,
ENCL_FOOD_ID AS food_id,
ENCL_SUPPLEMENTAL_DIET AS supplemental_diet,
ENCL_REMARK AS remark,
(CASE WHEN ENCL_MH_ROOM_YN = 'Y' THEN 1 ELSE 0 END) AS isMhRoom,
ENCL_MH_GROUP AS mh_group
FROM cnprcSrc.ZENCLOSURE;