SELECT
SB_AN_ID AS Id,
SB_SAMPLE_DATE,
SB_FREEZER_LOCATION_BOX AS locationBox,
SB_FREEZER_LOCATION_SLOT AS locationSlot,
SB_VIRAL_PRECAUTION_FLAG AS viralPrecautionFlag,
OBJECTID as objectid
FROM cnprcSrc.ZSERUM_BANK;