SELECT
OBJECTID || '-' || SNO_TOPOGRAPHY_CODE  AS objectid,
DATE_TIME
FROM cnprcSrc.ASNOMED WHERE SNO_TOPOGRAPHY_CODE IS NOT NULL AND SNO_DATE > to_date('01-01-1900', 'DD-MM-YYYY')

UNION ALL

SELECT
OBJECTID || '-' || SNO_MORPHOLOGY_CODE AS objectid,
DATE_TIME
FROM cnprcSrc.ASNOMED WHERE SNO_MORPHOLOGY_CODE IS NOT NULL AND SNO_DATE > to_date('01-01-1900', 'DD-MM-YYYY')

UNION ALL

SELECT
OBJECTID || '-' || SNO_ETIOLOGY_CODE AS objectid,
DATE_TIME
FROM cnprcSrc.ASNOMED WHERE SNO_ETIOLOGY_CODE IS NOT NULL AND SNO_DATE > to_date('01-01-1900', 'DD-MM-YYYY')

UNION ALL

SELECT
OBJECTID || '-' || SNO_FUNCTION_CODE AS objectid,
DATE_TIME
FROM cnprcSrc.ASNOMED WHERE SNO_FUNCTION_CODE IS NOT NULL AND SNO_DATE > to_date('01-01-1900', 'DD-MM-YYYY')

UNION ALL

SELECT
OBJECTID || '-' || SNO_DISEASE_CODE AS objectid,
DATE_TIME
FROM cnprcSrc.ASNOMED WHERE SNO_DISEASE_CODE IS NOT NULL AND SNO_DATE > to_date('01-01-1900', 'DD-MM-YYYY')

UNION ALL

SELECT
OBJECTID || '-' || SNO_PROCEDURE_CODE AS objectid,
DATE_TIME
FROM cnprcSrc.ASNOMED WHERE SNO_PROCEDURE_CODE IS NOT NULL AND SNO_DATE > to_date('01-01-1900', 'DD-MM-YYYY')

UNION ALL

SELECT
OBJECTID || '-' || SNO_OCCUPATION_CODE AS objectid,
DATE_TIME
FROM cnprcSrc.ASNOMED WHERE SNO_OCCUPATION_CODE IS NOT NULL AND SNO_DATE > to_date('01-01-1900', 'DD-MM-YYYY');

