SELECT
VI_ANIMAL_ID AS Id,
VI_SAMPLE_DATE,
VI_TEST_DATE AS testDate,
VI_TARGET AS target,
VI_VIRUS AS virus,
VI_TEST_METHOD AS method,
VI_SAMPLE_TYPE AS sampleType,
VI_PURPOSE AS purpose,
VI_RESULT AS result,
VI_OPTICAL_DENSITY AS opticalDensity,
VI_TITRATION AS titration,
VI_LAB AS lab,
VI_LOCATION AS location,
VI_COMMENT AS remark
FROM cnprcSrc.VITALS_VIROLOGY_VIEW
WHERE VI_SAMPLE_DATE > to_date('01-01-1900', 'DD-MM-YYYY');
