SELECT
OBJECTID as objectid,
DATE_TIME
FROM cnprcSrc.AWEIGHING
WHERE WT_AUD_CODE = 'D'
UNION
SELECT
OBJECTID as objectid,
DATE_TIME
FROM cnprcSrc.AANIMAL
WHERE AN_AUD_CODE = 'D'
UNION
SELECT
OBJECTID as objectid,
DATE_TIME
FROM cnprcSrc_aud.APRIMED_TREATMENT
WHERE AUD_CODE = 'D'
UNION
SELECT
OBJECTID as objectid,
DATE_TIME
FROM cnprcSrc_aud.ABIO_BEHAVIORAL_ASSESSMENT
WHERE BBA_AUD_CODE = 'D'
UNION
SELECT
OBJECTID as objectid,
DATE_TIME
FROM cnprcSrc_aud.APATH_REPORT
WHERE PR_AUD_CODE = 'D'
