SELECT
WT_AN_ID AS Id,
WT_DATE AS weightDate,
OBJECTID AS encounterId,
OBJECTID AS objectId,
'Weight' AS remark,
DATE_TIME
FROM cnprcSrc.ZWEIGHING
WHERE
WT_WEIGHT_KG IS NOT NULL
AND (WT_TB_TEST1_TYPE IS NULL AND WT_TB_TEST2_TYPE IS NULL)
AND WT_DATE > to_date('01-01-1900', 'DD-MM-YYYY')

UNION ALL

SELECT
WT_AN_ID AS Id,
WT_DATE AS weightDate,
OBJECTID AS encounterId,
OBJECTID AS objectId,
'TB Weight' AS remark,
DATE_TIME
FROM cnprcSrc.ZWEIGHING
WHERE
WT_WEIGHT_KG IS NOT NULL AND
(WT_TB_TEST1_TYPE IS NOT NULL OR WT_TB_TEST2_TYPE IS NOT NULL) AND
WT_DATE > to_date('01-01-1900', 'DD-MM-YYYY')

UNION ALL

SELECT
AN_ID AS Id,
AN_BIRTH_DATE AS weightDate,
OBJECTID AS encounterId,
OBJECTID AS objectId,
'Birth Weight' AS remark,
DATE_TIME
FROM cnprcSrc.ZANIMAL
WHERE
AN_BIRTH_WT_KG IS NOT NULL AND
AN_BIRTH_DATE > to_date('01-01-1900', 'DD-MM-YYYY')

UNION ALL

SELECT
PT_AN_ID AS Id,
PT_START_DATE AS weightDate,
OBJECTID AS encounterId,
OBJECTID AS objectId,
'Treatment Weight' AS remark,
DATE_TIME
FROM cnprcSrc.ZPRIMED_TREATMENT
WHERE
PT_AN_WT_USED IS NOT NULL AND
PT_START_DATE > to_date('01-01-1900', 'DD-MM-YYYY')

UNION ALL

SELECT
ANIMID AS Id,
TEST_DAT AS weightDate,
OBJECTID AS encounterId,
OBJECTID AS objectId,
'Behavior Assessment Weight' AS remark,
DATE_TIME
FROM cnprcSrc.ZBIO_BEHAVIORAL_ASSESSMENT
WHERE
WEIGHT IS NOT NULL AND
TEST_DAT > to_date('01-01-1900', 'DD-MM-YYYY')

UNION ALL

SELECT
PR_AN_ID AS Id,
PR_DATE AS weightDate,
OBJECTID AS encounterId,
OBJECTID AS objectId,
'Biopsy/Necropsy Weight' AS remark,
DATE_TIME
FROM cnprcSrc.ZPATH_REPORT
WHERE
PR_BODY_WEIGHT_GRAMS IS NOT NULL AND
PR_DATE > to_date('01-01-1900', 'DD-MM-YYYY');