SELECT
t.PT_AN_ID AS Id,
t.PT_START_DATE as startDate,
t.PT_CNPRC_PROJECT AS project,
s.ASNO_CODE_1 AS code,
t.PT_TREATMENT_VOLUME AS volume,
t.PT_TREATMENT_VOLUME_UNITS AS vol_units,
t.PT_DRUG_CONCEN_PER_UNIT AS concentration,
t.PT_DRUG_CONCEN_UNITS AS conc_units,
t.PT_TOTAL_DOSE_AMOUNT AS amount,
t.PT_TOTAL_DOSE_UNITS AS amount_units,
t.PT_ROUTE AS route,
t.PT_END_DATE AS enddate,
t.PT_FREQUENCY_USED AS frequency,
t.PT_DOSE_PER_UNIT_USED AS dosage,
t.PT_DOSE_UNITS AS dosage_units,
t.PT_TREATMENT_TYPE AS category,
t.PT_SEQ AS seq,
t.PT_FORMULARY_NAME_FK AS formularyNameFk,
t.PT_FORMULARY_DOSING_FK AS formularyDosingFk,
t.PT_DRUG_CALC_DATA_AVAIL_YN AS drugCalcDataAvailable,
t.PT_AN_WT_OVERRIDE_YN AS weightOverride,
t.PT_AN_WT_DB AS weightDb,
t.PT_AN_WT_USED AS weightUsed,
t.PT_DRUG_CALC_OVERRIDE_YN AS drugCalOverride,
t.PT_DRUG_NAME AS drugName,
t.PT_DOSE_PER_UNIT_DB AS dosePerUnit,
t.PT_FREQUENCY_DB AS frequencyDb,
t.PT_DURATION_DB AS durationDb,
t.PT_DURATION_USED AS durationUsed,
t.PT_DOSING_NOTES AS dosingNotes,
t.PT_USER_COMMENT AS userComment,
t.PT_NEXT_PRINT_FLAG_UPDATE_YN AS nextPrintFlagUpdate,
t.PT_TREATMENT_CREATED_BY AS treatmentCreator,
t.PT_PRESCRIBING_VETERINARIAN AS prescribingVet,
t.PT_BILLING_ITEM_CODE AS billingItemCode,
t.PT_BILLING_AMOUNT AS billingAmt,
t.PT_CNPRC_BILLING_ID AS cnprcBillingId,
t.PT_RX_INVALID_OR_NEVER_GIVEN AS rxInvalidOrNeverGiven
-- AS objectid,
FROM cnprcSrc.ZPRIMED_TREATMENT t
LEFT JOIN
cnprcSrc.ZAN_SNOMED s
ON t.PT_AN_ID = s.ASNO_AN_ID;