SELECT
AC_CNPRC_ID AS Id,
AC_TEST_DATE,
AC_SEQPK AS seq_pk,
AC_COMMENT AS remark,
AC_TOT_WBC AS total_wbc,
AC_RBC AS rbc,
AC_HGB AS hgb,
AC_HCT AS hct,
AC_MCV AS mcv,
AC_MCH AS mch,
AC_MCHC AS mchc,
AC_PLATELETS AS platelets,
AC_PLAS_PROT AS plas_prot,
AC_FIBROGEN AS fibrogen,
AC_NEUT_BAND AS neut_band,
AC_NEUT_BAND_PER AS neut_band_per,
AC_NEUT_SEG AS neut_seg,
AC_NEUT_SEG_PER AS neut_seg_per,
AC_LYMPHOCYTE AS lymphocyte,
AC_LYMPHOCYTE_PER AS lymphocyte_per,
AC_MONOCYTE AS monocyte,
AC_MONOCYTE_PER AS monocyte_per,
AC_EOSINOPHIL AS eosinophil,
AC_EOSINOPHIL_PER AS eosinophil_pe,
AC_BASOPHIL AS basophil,
AC_BASOPHIL_PER AS basophil_per
FROM cnprcSrc_rd.ASTHMA_CBC

UNION ALL

SELECT
AC_CNPRC_ID AS Id,
AC_TEST_DATE,
NULL AS seq_pk,
AC_COMMENT AS remark,
AC_TOT_WBC AS total_wbc,
AC_RBC AS rbc,
AC_HGB AS hgb,
AC_HCT AS hct,
AC_MCV AS mcv,
AC_MCH AS mch,
AC_MCHC AS mchc,
AC_PLATELETS AS platelets,
AC_PLAS_PROT AS plas_prot,
AC_FIBROGEN AS fibrogen,
AC_NEUT_BAND AS neut_band,
AC_NEUT_BAND_PER AS neut_band_per,
AC_NEUT_SEG AS neut_seg,
AC_NEUT_SEG_PER AS neut_seg_per,
AC_LYMPHOCYTE AS lymphocyte,
AC_LYMPHOCYTE_PER AS lymphocyte_per,
AC_MONOCYTE AS monocyte,
AC_MONOCYTE_PER AS monocyte_per,
AC_EOSINOPHIL AS eosinophil,
AC_EOSINOPHIL_PER AS eosinophil_pe,
AC_BASOPHIL AS basophil,
AC_BASOPHIL_PER AS basophil_per
FROM cnprcSrc_rd.ASTHMA_CBC_LOAD;