SELECT id,
(select flags.flag.value where flags.flag.value = 'HGL2') "HGL2",
(select flags.flag.value where flags.flag.value = 'HJS2') "HJS2",
(select flags.flag.value where flags.flag.value = 'HLH2') "HLH2",
(select flags.flag.value where flags.flag.value = 'HODK') "HODK",
(select flags.flag.value where flags.flag.value = 'HOGL') "HOGL",
(select flags.flag.value where flags.flag.value = 'HOJS') "HOJS",
(select flags.flag.value where flags.flag.value = 'HOJV') "HOJV",
(select flags.flag.value where flags.flag.value = 'HOLG') "HOLG",
(select flags.flag.value where flags.flag.value = 'HOLH') "HOLH",
(select flags.flag.value where flags.flag.value = 'HOMS') "HOMS",
(select flags.flag.value where flags.flag.value = 'HOPM') "HOPM",
(select flags.flag.value where flags.flag.value = 'HOSG') "HOSG",
(select flags.flag.value where flags.flag.value = 'HOVB') "HOVB",
(select flags.flag.value where flags.flag.value = 'HOVL') "HOVL",
(select flags.flag.value where flags.flag.value = 'HOWA') "HOWA",
(select flags.flag.value where flags.flag.value = 'HOYK') "HOYK",
(select flags.flag.value where flags.flag.value = 'HYK2') "HYK2"
from study.flags