SELECT id,
(select 'HGL2' where flags.values like '%HGL2%') "HGL2",
(select 'HJS2' where flags.values like '%HJS2%') "HJS2",
(select 'HLH2' where flags.values like '%HLH2%') "HLH2",
(select 'HODK' where flags.values like '%HODK%') "HODK",
(select 'HOGL' where flags.values like '%HOGL%') "HOGL",
(select 'HOJS' where flags.values like '%HOJS%') "HOJS",
(select 'HOJV' where flags.values like '%HOJV%') "HOJV",
(select 'HOLG' where flags.values like '%HOLG%') "HOLG",
(select 'HOLH' where flags.values like '%HOLH%') "HOLH",
(select 'HOMS' where flags.values like '%HOMS%') "HOMS",
(select 'HOPM' where flags.values like '%HOPM%') "HOPM",
(select 'HOSG' where flags.values like '%HOSG%') "HOSG",
(select 'HOVB' where flags.values like '%HOVB%') "HOVB",
(select 'HOVL' where flags.values like '%HOVL%') "HOVL",
(select 'HOWA' where flags.values like '%HOWA%') "HOWA",
(select 'HOYK' where flags.values like '%HOYK%') "HOYK",
(select 'HYK2' where flags.values like '%HYK2%') "HYK2"
from study.DemographicsActiveFlags flags